/* Fragen für "Wer würde eher …?" – familientauglich, ohne Gemeinheiten.
   Gespeichert ohne den Anfang "Wer würde eher" und ohne Fragezeichen,
   beides setzt das Spiel beim Anzeigen davor bzw. dahinter. */
(function (window) {
  'use strict';
  var TG = window.TG || (window.TG = {});

  TG.wwePack = {
    /* Hochzählen, wenn Fragen dazukommen – geteilte Codes bleiben dadurch
       nachvollziehbar, auch wenn sich das Deck später ändert. */
    version: 1,
    questions: [
      /* --- unterwegs --- */
      'im Stau laut mitsingen',
      'als Erste:r fragen „Sind wir bald da?“',
      'im Auto einschlafen, bevor die Fahrt richtig losgeht',
      'die Landkarte verkehrt herum halten',
      'den Koffer erst am Abend vorher packen',
      'drei Paar Schuhe zu viel einpacken',
      'die Zahnbürste zu Hause vergessen',
      'an jeder Raststätte aufs Klo müssen',
      'dem Navi widersprechen',
      'sich im Parkhaus verlaufen',
      'beim Wandern zuerst schlappmachen',
      'die Mütze im Restaurant liegen lassen',
      'am Strand einschlafen und einen Sonnenbrand bekommen',
      'sich beim Zelten vor jedem Geräusch erschrecken',
      'auf einer langen Fahrt die ganze Zeit die Musik aussuchen',
      'mitten in der Nacht losfahren wollen',
      'eine Abkürzung nehmen, die viel länger dauert',
      'am Flughafen drei Stunden zu früh sein',
      'im Hotel zuerst das Schwimmbad suchen',
      'das Souvenirregal leer kaufen',
      'bei einer Pause als Letzte:r wieder im Auto sitzen',
      'unterwegs jedes Tier begrüßen',
      'zuerst „Ich hab’s gesehen!“ rufen',
      'die längste Strecke am Stück fahren',

      /* --- Tiere --- */
      'einen Elefanten als Haustier wollen',
      'eine Spinne nach draußen tragen',
      'mit einem Hund um die Wette rennen',
      'einer Kuh Guten Tag sagen',
      'vor einer Gans weglaufen',
      'einen Igel im Garten füttern',
      'mit Delfinen schwimmen gehen',
      'einem Papagei Blödsinn beibringen',
      'ein Eichhörnchen zähmen wollen',
      'mit einem Pferd sprechen, als würde es antworten',
      'einen Schmetterling stundenlang beobachten',
      'zehn Katzen gleichzeitig adoptieren',

      /* --- Essen --- */
      'Pommes zum Frühstück essen',
      'die ganze Packung Kekse allein schaffen',
      'etwas probieren, das sehr komisch aussieht',
      'Ketchup auf alles tun',
      'im Eisladen zehn Minuten überlegen',
      'kalte Pizza zum Frühstück essen',
      'ein Gericht bestellen, dessen Namen sie oder er nicht aussprechen kann',
      'Ananas auf die Pizza tun',
      'beim Kochen alles anbrennen lassen',
      'heimlich vom Teller der anderen naschen',
      'eine Zitrone ohne Grimasse essen',
      'den letzten Keks abgeben',
      'beim Backen den Teig wegnaschen',
      'eine ganze Wassermelone allein essen',

      /* --- Mut und Abenteuer --- */
      'Bungee-Jumping ausprobieren',
      'im Gruselfilm die Augen zuhalten',
      'bei Regen im See baden',
      'eine Nacht allein im Wald verbringen',
      'mit dem Fallschirm springen',
      'auf den höchsten Turm steigen',
      'in einer Höhle als Erste:r vorgehen',
      'barfuß durch jede Pfütze springen',
      'in der Achterbahn in die erste Reihe wollen',
      'ohne Zögern ins kalte Wasser springen',
      'bei Gewitter nach draußen wollen',
      'einen Berg vor Sonnenaufgang besteigen',
      'im Dunkeln in den Keller gehen',
      'eine Wildwasserfahrt machen',

      /* --- Alltag und Eigenheiten --- */
      'eine Woche ohne Handy aushalten',
      'erst aufräumen, wenn Besuch kommt',
      'eine Stunde zu spät kommen',
      'sich über eine Kleinigkeit riesig freuen',
      'jeden Tag denselben Pullover tragen',
      'morgens als Erste:r wach sein',
      'den Wecker fünfmal ausmachen',
      'sich beim Einkaufen verquatschen',
      'dieselbe Geschichte dreimal erzählen',
      'absichtlich verlieren, damit jemand anders gewinnt',
      'bei einem Streit als Erste:r einlenken',
      'lachen, wenn eigentlich Ruhe sein müsste',
      'eine Überraschungsparty organisieren',
      'ein Geheimnis versehentlich ausplaudern',
      'auf jedem Foto die Augen zu haben',
      'im Supermarkt zur Musik tanzen',
      'beim Singen den Text erfinden',
      'eine ganze Serie an einem Tag schauen',
      'jeden Tag dasselbe Frühstück essen',
      'im Winter im T-Shirt rausgehen',
      'beim Quiz alle Antworten wissen',
      'die Bedienungsanleitung wirklich lesen',
      'ein Regal ohne Anleitung aufbauen',
      'beim Puzzle das letzte Teil verstecken',
      'aus Versehen das Falsche bestellen',
      'sich stundenlang an einem Rätsel festbeißen',
      'beim Brettspiel am meisten mitfiebern',
      'beim Kartenspiel schummeln',
      'die Fernbedienung verlegen',
      'den ganzen Sonntag im Schlafanzug bleiben',
      'die Pflanzen vergessen zu gießen',
      'beim Aufräumen alles in eine Kiste stopfen',
      'die Geburtstage aller auswendig wissen',
      'sofort helfen, wenn jemand etwas Schweres trägt',
      'die Musik zu laut aufdrehen',
      'bei einem Familienfoto Faxen machen',
      'den Abwasch aufschieben',
      'die schönste Postkarte schreiben',
      'eine Kerze vergessen auszupusten',
      'sich beim Wandern verlaufen und es toll finden',
      'beim Film als Erste:r weinen',
      'die meisten Fotos vom Essen machen',
      'einen Regenschirm im Bus liegen lassen',

      /* --- Träume und Zukunft --- */
      'Astronaut:in werden',
      'auf dem Mars leben wollen',
      'eine eigene Insel kaufen',
      'in die Zukunft reisen',
      'lieber fliegen als unsichtbar sein können',
      'mit Tieren sprechen wollen',
      'ein Buch über das eigene Leben schreiben',
      'berühmt werden wollen',
      'einen Schatz suchen gehen',
      'in einem Baumhaus wohnen',
      'einen Roboter als besten Freund haben',
      'eine neue Sprache in einer Woche lernen wollen',
      'im Zirkus auftreten',
      'eine Achterbahn erfinden',
      'auf einem Bauernhof leben wollen',
      'einen Film drehen, in dem alle mitspielen müssen',
      'dieses Spiel gleich nochmal spielen wollen'
    ]
  };
})(window);
